export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  STAFF: "STAFF",
  SCRUB_NURSE: "SCRUB_NURSE",
  OT_TECHNICIAN: "OT_TECHNICIAN",
  ANESTHESIOLOGIST:"ANESTHESIOLOGIST",
  ANESTHESIA_TECHNICIAN: "ANESTHESIA_TECHNICIAN",
  SURGEON: "SURGEON",
  NURSE: "NURSE",
  RECEPTIONIST: "RECEPTIONIST",
  DOCTOR: "DOCTOR",
};