import { ROLES } from "../constants/roles";

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: {
    canAccessDashboard: true,
    canManageHospital: true,
    canManageAdmins: true,
    canManageStaff: false,
    canManageOT: false,
    canManageOTRooms: false,
    canManageOTItems: false,
    canManageOTWard: false,
    canManageEquipment: false,
    canManageOperations: false,
    canManageRooms: false,
    canManageWards: false,
    canManagePreOP: false,
    canManageIntraOP: false,
    canManageIVFluids: false,
    canManageVitals: false,
  },
  [ROLES.ADMIN]: {
    canAccessDashboard: true,
    canManageHospital: false,
    canManageAdmins: false,
    canManageStaff: true,
    canManageOT: true,
    canManageOTRooms: true,
    canManageOTItems: true,
    canManageOTWard: true,
    canManageEquipment: true,
    canManageOperations: true,
    canManageRooms: false,
    canManageWards: false,
    canManagePreOP: false,
    canManageIntraOP: false,
    canManageIVFluids: false,
    canManageVitals: false,
  },
  [ROLES.RECEPTIONIST]: {
    canAccessDashboard: false,
    canManageHospital: false,
    canManageAdmins: false,
    canManageStaff: false,
    canManageOT: false,
    canManageOTRooms: false,
    canManageOTItems: false,
    canManageOTWard: false,
    canManageEquipment: false,
    canManageOperations: true,
    canManageRooms: true,
    canManageWards: true,
    canManagePreOP: false,
    canManageIntraOP: false,
    canManageIVFluids: false,
    canManageVitals: false,
  },
  [ROLES.SURGEON]: {
    canAccessDashboard: false,
    canManageHospital: false,
    canManageAdmins: false,
    canManageStaff: false,
    canManageOT: false,
    canManageOTRooms: false,
    canManageOTItems: false,
    canManageOTWard: false,
    canManageEquipment: false,
    canManageOperations: false,
    canManageRooms: false,
    canManageWards: false,
    canManagePreOP: true,
    canManageIntraOP: true,
    canManageIVFluids: true,
    canManageVitals: true,
  },
  // Baaki roles ke liye baad mein add karna
  [ROLES.DOCTOR]: {},
  [ROLES.NURSE]: {},
  [ROLES.STAFF]: {},
};

export const hasPermission = (role, permission) => {
  return ROLE_PERMISSIONS[role]?.[permission] ?? false;
};